before:
  hooks:
    - go mod download

build:
  main: cmd/bud/main.go
  # binary: bud

  ldflags: -s -w -X "main.Version={{.Tag}} [{{.Date}}]"

  env:
    - CGO_ENABLED=0

  goos:
    - darwin
    - linux

  goarch:
    - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
