language: go

go:
- 1.8
- 1.9
# - master

install:
- go get -u github.com/golang/dep/cmd/dep
- dep ensure
script:
- make lint
- make test

# jobs:
#   include:
#     - stage: deploy
#       script: ...
