up:
  - go: 1.9.5
  - custom:
      met?: dep status 2> /dev/null > /dev/null
      meet: dep ensure

commands:
  testup:
    desc: Build, install and run the development version
    run: go install && dad up

  test:
    desc: Run the unittests
    run: script/test

  integration:
    desc: Run the integration tests
    run: script/integration_test

  lint:
    desc: Lint the project
    run: script/lint

  ci:
    desc: Run all tests as CI would do
    run: script/test && script/integration_test && script/lint

  release:
    desc: Create a new release
    run: script/release

  godoc:
    desc: Starting GoDoc server on http://0.0.0.0:6060
    run: (sleep 1; open http://0.0.0.0:6060)& godoc -http=:6060

  install-dev:
    desc: Install dad in the GOROOT
    run: |
      go install -ldflags "-X main.Version=$(git describe --tags --dirty --always)"
      [ -e "/usr/local/bin/dad" ] && sudo rm /usr/local/bin/dad || true

  uninstall:
    desc: uninstall dad from /usr/local/bin/ and Go installation
    run: |
      [ -e "/usr/local/bin/dad" ] && sudo rm -v /usr/local/bin/dad
      [ -e "$GOPATH/bin/dad" ] && sudo rm -v $GOPATH/bin/dad
