up:
  - go: 1.9.2
  - [a, list]
  - python: 3.6.4rc1
  - pip:
    - requirements.txt
  - pipfile
  - custom:
      met?: brew info upx 2> /dev/null > /dev/null
      meet: brew install upx
  - custom:
      met?: dep status 2> /dev/null > /dev/null
      meet: dep ensure

commands:
  testup:
    desc: Build, install and run the development version
    run: go install && dad up

  test:
    desc: Run the tests
    run: script/test

  lint:
    desc: Lint the project
    run: script/lint

  godoc:
    desc: Starting GoDoc server on http://0.0.0.0:6060
    run: (sleep 1; open http://0.0.0.0:6060)& godoc -http=:6060

  install:
    desc: Install dad in the GOROOT
    run: go install -ldflags "-X main.Version=$(git describe --tags --dirty --always)"

  uninstall:
    desc: uninstall dad from /usr/local/bin/ and Go installation
    run: |
      [ -e "/usr/local/bin/dad" ] && sudo rm -v /usr/local/bin/dad
      [ -e "$GOPATH/bin/dad" ] && sudo rm -v $GOPATH/bin/dad

  # Test commands
  fail:
    desc: test command that fail
    run: false

  multilines:
    desc: test command with more than one line
    run: |
      # line one
      # line two
      # line three
