up:
  # - go: 1.9.2
  - python: 3.6.4rc1
  # - pip:
  #   - requirements.txt
  #   - requirements-dev.txt
  - custom:
      met?: 'false'
      meet: go get github.com/golang/dep/cmd/dep
  - custom:
      met?: 'false'
      meet: go get gopkg.in/alecthomas/gometalinter.v1
  - custom:
      met?: brew info upx 2> /dev/null > /dev/null
      meet: brew install upx
  - custom:
      met?: 'false'
      meet: 'false'

commands:
  testup:
    desc: Build, install and run the development version
    run: go install && dad up

  test:
    desc: Run the tests
    run: script/test

  lint:
    desc: Lint the project
    run: script/lint

  docserve:
    desc: Starting GoDoc server on http://0.0.0.0:6060
    run: godoc -http=:6060
