up:
  # - python: 3.6.3
  - pip:
    - requirements.txt
    - requirements-dev.txt
  - custom:
      met?: "false"
      meet: echo POIPOI POIPOI

commands:
  test:
    desc: Run tests
    run:
      make test

  lint:
    run: make lint
